name: 'action-update-dprint-plugins'
description: 'Update dprint plugins in dprint.json config file'
author: 'Kenichi Kamiya <kachick1@gmail.com>'
branding:
  icon: 'arrow-up-circle'
  color: 'blue'
inputs:
  base-branch:
    description: 'The branch into which you want updating PR merged'
    required: true
  auto-merge:
    description: 'The updating PR will be auto merged if no change exist even after `dprint fmt`'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    # Referenced https://github.com/dprint/check/blob/2f1cf31537886c3bfb05591c031f7744e48ba8a1/action.yml#L16-L20
    - name: Install dprint
      shell: bash
      run: |
        curl -fsSL https://dprint.dev/install.sh | sh -s '' > /dev/null 2>&1
        echo "/home/runner/.dprint/bin" >> $GITHUB_PATH
    - name: Create branch
      run: |
        timestamp=`date +"%Y%m%d-%H%M-UTC"`
        git switch -c "action-update-dprint-plugins-$timestamp"
      shell: bash
    - name: Update plugins
      run: |
        ~/.dprint/bin/dprint config update
        git add .
        git commit -a -m 'chore: `dprint config update`'
      shell: bash
    - name: fmt
      run: |
        ~/.dprint/bin/dprint fmt
        (git add --intent-to-add . && git diff --exit-code) || git commit -a -m 'chore: `dprint fmt`'
      shell: bash
    - name: Create PR
      run: gh pr create --fill --base ${{ inputs.base-branch}}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
    # - name: Auto merge
    #   run: ...
    #   shell: bash
